const PAGARME_ENCRYPTION_KEY = (
  process && process.env.REACT_APP_PAGARME_ENVIRONMENT === 'live'
    ? process.env.REACT_APP_PAGARME_ENCRYPTION_KEY_PRD
    : process.env.REACT_APP_PAGARME_ENCRYPTION_KEY_STG
)

export default PAGARME_ENCRYPTION_KEY